import { defineConfig } from 'tsup';
import pkg from './package.json';

export default defineConfig((options) => ({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: false, // Generate types separately with tsc to work around TypeScript deprecation warnings during tsup's dts generation
  splitting: false,
  sourcemap: true,
  clean: !options.watch, // Don't wipe .d.ts files generated by tsc in watch/dev mode
  outDir: 'dist',
  define: {
    __SDK_VERSION__: JSON.stringify(pkg.version),
  },
}));
